#!/usr/bin/env bun
/**
 * Build the BSON resource tree under `resources/` from Google libphonenumber's
 * upstream metadata.
 *
 * Steps:
 *   1. clone google/libphonenumber into resources/libphonenumber
 *   2. for each locale + country code, parse the upstream <CC>.txt into a
 *      `{ prefix: description }` object and serialize to BSON
 *   3. parse `timezones/map_data.txt` into one global `timezones.bson`
 *   4. regenerate `src/locales.ts` with the up-to-date locale unions
 *
 * Run with `bun run preparemetadata`.
 */
import { execSync } from 'node:child_process';
import { createReadStream, lstatSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { createInterface } from 'node:readline';
import { serialize } from 'bson';

const ROOT = join(import.meta.dir, '..');
const RESOURCES = join(ROOT, 'resources');
const UPSTREAM = join(RESOURCES, 'libphonenumber');
const RESOURCE_BASE = join(UPSTREAM, 'resources');

const LINE_RE = /^([0-9]+)\|(.*)$/;

const isDir = (path: string): boolean => {
  try {
    return lstatSync(path).isDirectory();
  } catch {
    return false;
  }
};

async function loadPipeFile(file: string, stripPrefix = ''): Promise<Record<string, string>> {
  const data: Record<string, string> = {};
  const fileStream = createReadStream(file);
  const rl = createInterface({ input: fileStream, crlfDelay: Infinity });
  const ccRe = stripPrefix ? new RegExp(`^${stripPrefix}`) : null;

  for await (const line of rl) {
    const m = LINE_RE.exec(line);
    if (!m) continue;
    const [, nr, description] = m;
    if (!nr || !description) continue;
    const prefix = ccRe ? nr.replace(ccRe, '') : nr;
    data[prefix] = description;
  }
  return data;
}

async function prepareLocale(localePath: string, locale: string, kind: 'geocodes' | 'carrier'): Promise<void> {
  const fileRe = /[0-9]+\.txt/;
  const files = readdirSync(localePath).filter((source) => fileRe.test(source));
  for (const file of files) {
    const countryCode = basename(file, '.txt');
    const data = await loadPipeFile(join(localePath, file), countryCode);
    const dataPath = join(RESOURCES, kind, locale);
    mkdirSync(dataPath, { recursive: true });
    writeFileSync(join(dataPath, `${countryCode}.bson`), serialize(data));
  }
}

async function preparePath(dataPath: string, kind: 'geocodes' | 'carrier'): Promise<string[]> {
  const locales = readdirSync(dataPath).filter((source) => isDir(join(dataPath, source)));
  await Promise.all(locales.map((locale) => prepareLocale(join(dataPath, locale), locale, kind)));
  return locales;
}

async function prepareTimezones(): Promise<void> {
  const file = join(RESOURCE_BASE, 'timezones', 'map_data.txt');
  const data = await loadPipeFile(file);
  writeFileSync(join(RESOURCES, 'timezones.bson'), serialize(data));
}

async function main(): Promise<void> {
  mkdirSync(join(RESOURCES, 'geocodes'), { recursive: true });
  mkdirSync(join(RESOURCES, 'carrier'), { recursive: true });

  if (!isDir(UPSTREAM)) {
    console.log('Cloning google/libphonenumber…');
    // Hard-coded string — no user input is interpolated into the command.
    execSync('git clone --depth=1 https://github.com/google/libphonenumber', {
      cwd: RESOURCES,
      stdio: 'inherit',
    });
  }

  console.log('Preparing geocode tables…');
  const geoLocales = await preparePath(join(RESOURCE_BASE, 'geocoding'), 'geocodes');

  console.log('Preparing carrier tables…');
  const carrierLocales = await preparePath(join(RESOURCE_BASE, 'carrier'), 'carrier');

  console.log('Preparing timezone table…');
  await prepareTimezones();

  console.log('Updating src/locales.ts…');
  const locales = `/* THIS FILE IS AUTOGENERATED by scripts/prepare-metadata.ts */
export type GeocoderLocale = ${geoLocales.map((l) => `'${l}'`).join(' | ')};
export type CarrierLocale = ${carrierLocales.map((l) => `'${l}'`).join(' | ')};
`;
  writeFileSync(join(ROOT, 'src', 'locales.ts'), locales);

  console.log('✓ Done.');
}

main().catch((err) => {
  console.error('preparemetadata failed:', err);
  process.exit(1);
});
